### ISSUE TITLE
Null checks in functions are not considered

### ISSUE THREAD

**Issue by david-gang** [uber/NullAway#356] opened 2019-09-11 11:43 UTC
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.
This blows up:
```
public class A {
    @Nullable
    private String a;
    private void setA(String b){
        a = b;
    }
    private String getA() {
        checkA();
        return a;
    }
    private void checkA() {
        if(a == null){
            throw new NullPointerException("a is null");
        }
    }
}
```
> A.java:18: error: [NullAway] returning @Nullable expression from method with @NonNull return type

If i move the null check to the same function it works:
```
public class A {
    @Nullable
    private String a;
    private void setA(String b){
        a = b;
    }
    private String getA() {
        if(a == null){
            throw new NullPointerException("a is null");
        }
        return a;
    }
}

```

why can't nullaway infer that a is not null if it is not in the same function? 
  - [x] Please include the library version number, including the minor and patch version, in the issue text.
0.76

**Comment by msridhar** [comment] 2019-09-11 15:58
This is by design.  NullAway does type-based checking and relies entirely on function signatures and annotations to understand the behavior of called functions.  For cases where the invoked method is checking nullness of a method parameter, you can add an `@Contract("null -> fail")` annotation; see [the docs](https://github.com/uber/NullAway/wiki/Supported-Annotations#contracts).  This case is checking nullness of a field and is not yet supported.  We have an open issue on this; see #134.  I'm going to go ahead and close this one as a duplicate.

**Closed by msridhar** 2019-09-11 15:58 UTC

**Comment by david-gang** [comment] 2019-09-11 16:10
Thanks for your clarification!
