### ISSUE TITLE
Spring bean properties

### ISSUE THREAD

**Issue by ctcpip** [uber/NullAway#163] opened 2018-05-11 19:51 UTC
We have a similar issue as described in #94, but wanted to call out explicitly as it may not be quite the same.

We have a very common pattern of something like:

`private MyObject myObject;`

in a class, and its value is set via spring bean property injection.

These always yield initializer warnings.

Is our best option here to use `@SuppressWarnings("NullAway.Init")` everywhere we have a field like this?

or register `@Inject` in `ExcludedFieldAnnotations` -- but this seems to be effectively the same as `@SuppressWarnings("NullAway.Init")`

**Comment by ctcpip** [comment] 2018-05-11 20:03
it would be nice to be able to have some command line arg like: `XepOpt:NullAway:TreatAsInitialized=MyObject`, although that's probably painting with too wide of a brush...

**Comment by msridhar** [comment] 2018-05-11 20:13
Is there an annotation on the class indicating it is subject to the spring bean stuff?  If so maybe the `-XepOpt:NullAway:ExternalInitAnnotations` option will help?  See [here](https://github.com/uber/NullAway/wiki/Configuration#external-init-annotations).  If that's not useful, could you post a more complete code example?

**Comment by ctcpip** [comment] 2018-05-11 20:57
We can specify an annotation on that class, but `ExternalInitAnnotations` doesn't help with this problem, as I understand it.  Doesn't that only help within that class itself? ("we don’t check that the zero-arg constructor initializes all non-null fields")

Our issue here is that a different class (`B`) has a field which is the bean class (`A`) and results in `[NullAway] @NonNull field a not initialized`

**Comment by msridhar** [comment] 2018-05-11 21:00
Alright, not fully following :-)  Can you post a more complete code example?

**Comment by ctcpip** [comment] 2018-05-11 21:12
this is far from "complete" but I hope it is enough to illustrate... 

```
public class TehBean
{
  // here be codes
}

public class ConsumerOfTehBean
{

  private TehBean tehBean;

  public TehBean getTehBean()
  {
     return this.tehBean;
  }

  public void setTehBean(final TehBean tehBean)
  {
     this.tehBean = tehBean;
  }
}
```

in `applicationContext.xml`:

```
	<bean id="tehBean" class="org.something.cookie.TehBean">
	</bean>

	<bean id="consumerOfTehBean" class="org.something.biscuit.ConsumerOfTehBean">
		<property name="tehBean" ref="tehBean" />
	</bean>
```

**Comment by msridhar** [comment] 2018-05-11 21:25
Ok, I see the issue here.  The problem is with `ExternalInitAnnotations` we don't properly handle the case where the zero-argument constructor is missing.  I can try to fix that for the next release.

For the record, here is an example where things work.

```java
package fizz;
public @interface ExternalInit {}
```

```java
package fizz;
@ExternalInit
class Example {
  private Object field;
  Example() {}
  public Object getField() { return this.field; }
  public void setField(final Object f) { this.field = f; }
}
```
If I pass `-XepOpt:NullAway:ExternalInitAnnotations=fizz.ExternalInit` then NullAway does not warn on this code.  But, if I delete `Example() {}` then I still see a warning at the `private Object field;` line (which is buggy).

I'll work on fixing this.  Thanks for the report!  Note that even after the fix, you'll have to add an annotation like `@ExternalInit` on classes like `ConsumerOfTehBean` to get rid of the NullAway warning.  No plans to parse XML config in NullAway 😄

**Comment by ctcpip** [comment] 2018-05-11 21:52
then `@ExternalInit` is effectively the same in this case as `@SuppressWarnings("NullAway.Init")`, correct?

**Comment by ctcpip** [comment] 2018-05-11 21:53
wait- you said:  "@ExternalInit on classes like ConsumerOfTehBean"

how does that help with `private TehBean tehBean;` causing `[NullAway] @NonNull field tehBean not initialized` ?

**Comment by msridhar** [comment] 2018-05-11 22:15
That message means NullAway thinks that the field `tehBean` (which is assumed to be `@NonNull`) never gets initialized properly.  Adding the annotation on `ConsumerOfTehBean` tells NullAway that some other external magic initializes the `tehBean` field so don't worry about it.  Does that make sense?

> then `@ExternalInit` is effectively the same in this case as `@SuppressWarnings("NullAway.Init")`, correct?

Yes.  `@ExternalInit` would be helpful if you have many fields in a class and don't want to suppress warnings on each of them.  Plus it can more clearly convey how the initialization is happening.

**Comment by ctcpip** [comment] 2018-05-14 17:56
using `@ExternalInit` simply results in another message: `[NullAway] initializer method does not guarantee @NonNull fields upgradeManager, managerDao are initialized along all control-flow paths (remember to check for exceptions or early returns).`

so it looks like the SuppressWarnings is a better option for us in this case

**Comment by msridhar** [comment] 2018-05-14 18:02
@ctcpip two things:

1. There is a real bug here for the case where the no-argument constructor is not declared explicitly.  I need to fix that.  I'll cut a new release once I do.  That will make `@ExternalInit` more usable for your use case.

2. I said before that `@ExternalInit` is the same as `@SuppressWarnings("NullAway.Init")` but this was incorrect.  `@ExternalInit` only kicks in for zero-argument constructors.  If there is another constructor declared that takes arguments, it will still get checked.  `@SuppressWarnings("NullAway.Init")` will suppress checking of all constructors / initializers.

**Comment by ctcpip** [comment] 2018-05-14 18:17
Ok - we will try it after the next release.  Thank you @msridhar

**Comment by msridhar** [comment] 2018-05-15 21:42
@ctcpip the `@ExternalInit` functionality should be more usable in 0.4.6 which was just released

**Comment by alightsleeper** [comment] 2018-05-25 20:05
Hi @msridhar, I'm working with @ctcpip on implementing NullAway for our shared codebase. I just tested `@ExternalInit` using version 0.4.6, and it appears that this issue isn't fully resolved -- init errors are still being thrown unless there is an explicit zero-argument constructor.

Is there any significant advantage to using `@ExternalInit` over `@SuppressWarnings("NullAway.Init")`? Unless there is, I'm thinking we're better off just using the latter -- please advise.

**Comment by msridhar** [comment] 2018-05-26 16:34
@alightsleeper can you give a self-contained code example showing the problem with `@ExternalInit` throwing errors when there is no explicit constructor?  [Here](https://github.com/uber/NullAway/blob/master/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L190) is my simple test case with no zero-arg constructor.  Are you passing the `ExternalInitAnnotations` option like [here](https://github.com/uber/NullAway/blob/master/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L62)?

As I noted [above](https://github.com/uber/NullAway/issues/163#issuecomment-388908720), `@ExternalInit` is advantageous when you have constructors taking arguments, as those still get checked for initialization issues.  If you have no constructors at all, then `@ExternalInit` is the same as `@SuppressWarnings("NullAway.Init")` except there are fewer annotations to write.

**Comment by msridhar** [comment] 2018-05-29 23:02
@alightsleeper can you add `@java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.CLASS)` before  `public @interface ExternalInit` and see if that fixes it?  I think default retention is `SOURCE` which won't be good enough.

**Comment by alightsleeper** [comment] 2018-05-30 17:39
@msridhar per the javadocs default retention policy is CLASS, so setting that annotation on the ExternalInit interface had no effect. I also tried RUNTIME and SOURCE, no effect either.

For now, we'll just continue using version 0.4.5 and the more verbose `@SuppressWarnings("NullAway.Init")` and consider switching to `@ExternalInit` if we update NullAway version in the future. 

Thank you for your time and effort investigating this issue.

**Comment by msridhar** [comment] 2018-05-30 17:44
Ok, sorry it's not working.  I'll continue to investigate.

**Comment by msridhar** [comment] 2018-05-31 23:43
I think I might see the problem here.  @alightsleeper in your example `@ExternalInit` should be on the `FooController` class, not the `fooService` field.  Does that fix the problem?

**Comment by alightsleeper** [comment] 2018-06-04 17:20
@msridhar that's intentional -- we'd hoped to use `@ExternalInit` at the field level, to ensure that any fields added in the future that aren't initialized via spring bean injection and getters/setters are still caught. 

`@SuppressWarnings("NullAway.Init")` is working fine for our specific use case -- you can go ahead and close this issue.

**Comment by msridhar** [comment] 2018-06-04 18:12
Ah, ok, `@ExternalInit` is only supported on classes.  I think your use of `@SuppressWarnings("NullAway.Init")` is the right way to go.  If you were interested in contributing a NullAway [`Handler`](https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java) some day to read the XML directly we can brainstorm about that.  Thanks!

**Closed by msridhar** 2018-06-04 18:12 UTC
