### ISSUE TITLE
Proposal: Understand Optional isPresent/isEmpty/isAbsent

### ISSUE THREAD

**Issue by ZacSweers** [uber/NullAway#274] opened 2018-12-17 04:49 UTC
Right now NullAway can understand cases like AutoValue where 

```java
if (a.foo() != null) {
  a.foo().bar();
}
```

I propose adding support for an `Optional` analogue:

```java
if (fooOptional.isPresent()) {
  fooOptional.get().bar(); // Implicitly understood to be safe
}
```

I think this is a good fit for NullAway since `Optional` is Java 8/Guava's alternative to `null` in common cases, and has precedent for this kind of data flow awareness of "was null-checked already". This would just be a different flavor.

**Comment by msridhar** [comment] 2018-12-18 01:00
I like this idea, and agree it's not far from what NullAway already does.  Basically we'd want to model the presence state of Optionals and report errors on bad `get()` calls.  But we could pretty much model presence as nullability of the "contents" of the Optional.

@lazaroclapp what do you think?  I'm not sure if this would work best in a Handler or just as a core part of NullAway.

Of course implementation would take some work so we'd need to figure out how that would get done 😄

**Comment by lazaroclapp** [comment] 2018-12-18 01:13
Definitely fits with the model, not sure how it will fit with the code, thought. My impression is that the change would be a bit more involved than what what can currently be done with a Handler, but I am not sure. Basically, a duplicate of the entire `Nullness` dataflow propagation, but for a new `Emptyness` type system? 

Tentatively assigning to self so I can take a look when I am back in Jan, but feel free to take a look at how hard this would be if you are interested in it and have enough time :)

**Closed** 2019-03-06 23:42 UTC
