### ISSUE TITLE
Is there any way to handle null-firendly DTOs?

### ISSUE THREAD

**Issue by pablogrisafi1975** [uber/NullAway#459] opened 2021-04-08 18:00 UTC
I have some typical DTO classes like 

       public class User{
               private String firstName;
               private String lastName;
              // public getters and setters
       }

Every field can be null, every setter can accept null, every getter can return null.

Is there any way to marke the whole class as "Everything can be null" ? What is the recommended practice?

**Comment by msridhar** [comment] 2021-04-09 17:32
I think this is #94, which unfortunately we haven't had a chance to work on yet.  (If someone is interested, we'd love to get a PR!) For now, you'll have to add `@Nullable` annotations everywhere.  Arguably, if most of your code is annotated for NullAway with the unannotated-means-@NonNull default, adding `@Nullable` annotations to classes like these may make the code base more readable.

@lazaroclapp any other ideas here?

Duplicate of #94

**Comment by msridhar** [comment] 2021-04-09 17:32
Duplicate of #94

**Closed** 2021-07-27 00:40 UTC
