### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by wecheng** [uber/NullAway#484] opened 2021-05-31 11:52 UTC
I was following up the sample in below link to setup NullAway in my project, but I saw below NoSuchMethodError. Is there any suggestion for fixing this error?

https://gist.github.com/msridhar/6cacd429567f1d1ad9a278e06809601c

An exception has occurred in the compiler ((version info not available)). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.**NoSuchMethodError**: **com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector**;
	**at com.google.errorprone.BugCheckerInfo.customSuppressionAnnotations(BugCheckerInfo.java:144)**
	at com.google.errorprone.BugCheckerInfo.<init>(BugCheckerInfo.java:122)
	at com.google.errorprone.BugCheckerInfo.create(BugCheckerInfo.java:110)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:298)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:291)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:327)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:42)
	at com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:214)
	at com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:192)
	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:97)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:93)
	at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:113)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:46)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:36)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:36)
	at org.gradle.workers.internal.FlatClassLoaderWorker.execute(FlatClassLoaderWorker.java:31)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

> Task :Teams:compileDevDebugJavaWithJavac FAILED

**Comment by msridhar** [comment] 2021-05-31 23:44
@wecheng that example is out of date.  Can you let me know where it is linked from so I can update?

Your best bet for setting up NullAway on an Android project for now is to base the config on the `build.gradle` in the sample app:

https://github.com/uber/NullAway/blob/f8e9cbe4f6471330873c4c27e240c12fef92ddd1/sample-app/build.gradle

I'll try to update the self-contained gist soon.

**Comment by msridhar** [comment] 2021-05-31 23:47
@wecheng I just updated a couple version numbers in the gist.  Can you see if that works better?

**Comment by wecheng** [comment] 2021-06-01 02:44
@msridhar Where can I get these new version numbers in the gist? If I don't want to copy all code of NullAway to my project, I think I can try to use it by below dependency, right? What should be the latest version?

annotationProcessor "com.uber.nullaway:nullaway:0.9.1"

**Comment by msridhar** [comment] 2021-06-01 02:48
Yes that’s correct, and use Error Prone 2.4.0 as a minimum (latest version
is 2.7.1)

**Comment by wecheng** [comment] 2021-06-01 02:54
@msridhar So the latest version of NullAway is still 0.9.1?

**Comment by msridhar** [comment] 2021-06-01 03:12
Yes.  A new release is likely coming soon but not sure exactly when

**Comment by wecheng** [comment] 2021-06-01 10:18
Hi @msridhar  What is this path? How can i set it in my project?
annotationProcessor project(path: ":sample-library-model")

**Comment by msridhar** [comment] 2021-06-01 16:17
You can ignore that entry; it's just showing how to use a library model if you have one, but you probably don't.

**Comment by wecheng** [comment] 2021-06-02 13:55
@msridhar I am encountering a build error. Do you know how can I fix it?

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/24379059/120492932-17451180-c3ed-11eb-8944-efada4982bc9.png">

**Comment by msridhar** [comment] 2021-06-02 17:53
You need to make sure you have the errorprone gradle plugin enabled:

https://github.com/tbroyer/gradle-errorprone-plugin

**Comment by wecheng** [comment] 2021-06-03 14:02
@msridhar @tbroyer 
I followed this link https://github.com/tbroyer/gradle-errorprone-plugin to import error prone plugin to my project, but saw this error.

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/24379059/120657279-efba7b80-c4b6-11eb-9e4b-6a83f9a64241.png">

My updates:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/24379059/120657688-4d4ec800-c4b7-11eb-9c1b-0209d21c88b7.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/24379059/120657796-65264c00-c4b7-11eb-95db-d20a94a3abc8.png">

**Comment by msridhar** [comment] 2021-06-03 14:10
This looks like an issue with a wrong Guava version in the annotation processor path.  Do you have any customization around Guava versions?  If you could share a self-contained project that fails with the same error that would help.

**Comment by wecheng** [comment] 2021-06-03 15:53
@msridhar Thanks for your quick reply. I tried to update to use the same Guava version 22.0 with NullAway, but have the same error. In our project, versions.guava is 25.1-android, then I added another line to import Guava version 22.0.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/24379059/120674396-a07c4700-c4c6-11eb-9928-b388211292dd.png">

**Comment by msridhar** [comment] 2021-06-03 16:38
@wecheng I don't know what is going on.  Without a reproducible example, unfortunately, this is very hard to debug.  Our configuration works in our regression tests, so this must be something specific to your internal configuration.

**Comment by tbroyer** [comment] 2021-06-03 16:50
I don't know the configurations in an Android project, but could you share the result of `./gradlew :Teams:dependencies --configuration annotationProcessor`? (or the equivalent in an Android project)
Also check `./gradlew :Teams:dependencyInsight --configuration annotationProcessor --dependency com.google.guava:guava`.

**Comment by wecheng** [comment] 2021-06-04 12:24
@tbroyer 
./gradlew :Teams:dependencies --configuration annotationProcessor
![image](https://user-images.githubusercontent.com/24379059/120788992-978d8300-c563-11eb-8ef6-8e3c9b658f3a.png)

./gradlew :Teams:dependencyInsight --configuration annotationProcessor --dependency com.google.guava:guava
![image](https://user-images.githubusercontent.com/24379059/120800274-55b80900-c572-11eb-9373-bd72c8a0794c.png)

Actually, we added below line in the project gradle

api "com.google.guava:guava:${versions.guava}" // guava version is 25.1-android

**Comment by tbroyer** [comment] 2021-06-04 12:55
`annotationProcessor` is not the actual configuration used by `JavaCompile` tasks for their processor path, it's merged into more specific configurations (probably one per build variant, but I don't know Android development much), so maybe something like `nordenDebugAnnotationProcessor` or something like that.
Maybe try a `./gradlew dependencies` without `--configuration` filter to find the appropriate one; or maybe you could even explore the available configurations from Android Studio's "Gradle" pane (assuming it works the same as IntelliJ IDEA)

(also, copy/paste text from your console rather than screenshotting)

**Comment by msridhar** [comment] 2021-06-04 18:06
Also I see the NullAway version in your output is 0.7.10 which is old. I recommend using the latest version if possible.

**Comment by wecheng** [comment] 2021-06-07 02:04
@tbroyer @msridhar thanks for your helps on this build error. I tried to run ./gradlew dependencies and got more outputs. I can see below dependencies on error_prone_core.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/24379059/120949528-4fdf4500-c777-11eb-9f6e-b4e65b8f5388.png">

**Comment by tbroyer** [comment] 2021-06-07 07:47
So now we know that "you" try to run ErrorProne with a downgraded Guava version, one that does not have `com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector` (specifically here because of the Android flavor of the dependency, not the actual version).

The next thing to do is to get, from the `./gradlew dependencies`, the name of a configuration containing both ErrorProne and NullAway (and your annotation processors); one whose line does *not* end with `(n)`.
Once you have it, run `./gradlew dependencyInsight --dependency com.google.guava:guava --configuration theConfigurationName`, this will tell you **why** that version of Guava is being used here, and hopefully will be enough for you to fix your build.

**Comment by msridhar** [comment] 2021-06-07 16:28
Thanks, @tbroyer!  I am optimistic this issue should be fixable, since I don't see any reason why the Android flavor of Guava should need to be pulled into the annotation processor path.

**Comment by wecheng** [comment] 2021-06-08 12:54
@tbroyer I think I have found the root cause for that NoClassDefFoundError on the com.google.common.collect.Streams. My project is force-using guava 25.1-android which really doesn't have the class collect.Streams even I upgraded to 30.1.1-android for guava. Do you know which old errorprone version can be used without these new classes in guava 27(+)-jre? 


<img width="517" alt="image" src="https://user-images.githubusercontent.com/24379059/121187673-e6f0ed80-c89a-11eb-9b19-981f64ba5f5c.png">

**Comment by tbroyer** [comment] 2021-06-08 15:49
You shouldn't force the android flavor of Guava in every configuration indiscriminately; that should only be done in compilation classpath and runtime classpath kind of configurations.
I'd suggest you ask on an Android or Gradle support forum how to do that "properly" ("force" is a crutch, you should try to avoid it to begin with)
See https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html, or at a minimum exclude the annotation processor configurations from your resolution strategy that forces the version of Guava.

**Comment by msridhar** [comment] 2021-07-14 18:07
I'm going to close this under the assumption that it's not a NullAway issue

**Closed by msridhar** 2021-07-14 18:07 UTC
