### ISSUE TITLE
No Build errors for a sample Android Application

### ISSUE THREAD

**Issue by AbhishekIIScPhD** [uber/NullAway#892] opened 2024-01-10 04:49 UTC
Working with NullAway Master branch

I have been not able to detect any build failures due to possible Null Dereferences the application. I have followed the instructions from the README.md for the project. 

Please consider updating the README.md and also suggest any changes that may be required for the build setup.

Please find the sample application , https://github.com/AbhishekIIScPhD/AndroidNullAway here.

**Comment by msridhar** [comment] 2024-01-13 16:50
Duplicate of #891

**Closed by msridhar** 2024-01-13 16:50 UTC
